name: dooit
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Graphik
      fonts:
        - asset: assets/fonts/Graphik-Medium.otf
        - asset: assets/fonts/Graphik-Regular.otf
        - asset: assets/fonts/Graphik-Semibold.otf
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SFProDisplay-Regular.otf
        - asset: assets/fonts/SFProDisplay-Medium.otf

